<a href="https://colab.research.google.com/github/Saiyyam24/deeplearning_practice_project/blob/main/lstm_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Generator

In [ ]:
text = '''
Apply for our LIVE Python Developer Placement Program - https://codingwise.in/pythondevelopercourse/
Assignment: Phonebook Application
Overview
In this project, you will create a simple Phonebook application using Python. This application will allow users to add, search for, delete, and list phonebook entries. The project focuses on reinforcing your understanding of Python's basic concepts, particularly conditional statements and dictionaries.
Objectives
Understand and apply Python dictionaries to store phonebook entries.
Use conditional statements to handle different user actions.
Implement CRUD (Create, Read, Update, Delete) operations on the phonebook entries.
Requirements
Python: Ensure Python is installed on your system.
Text Editor: Any text editor for writing Python code (e.g., VSCode, PyCharm, Sublime Text).
Project Structure
Your application should be able to:
Add a New Contact: Prompt the user for the name and phone number of a new contact and add it to the phonebook.
Search for a Contact: Allow the user to search for a contact by name and display the contact's phone number.
Delete a Contact: Enable the user to delete a contact by name.
List All Contacts: Display all contacts in the phonebook.
Exit: Terminate the application.
Implementation Steps
Step 1: Setup Your Project
Create a new Python file named phonebook.py.
Open this file in your chosen text editor.
Step 2: Initialize the Phonebook
At the beginning of your program, create an empty dictionary to store your contacts. Each contact name will be a key, and the associated phone number will be the value.
Step 3: User Interface
Implement a loop that continuously displays a menu of options to the user until they choose to exit. Use input() to read the user's choice and if-else statements to handle different actions based on the choice.
Step 4: Implementing CRUD Operations
Add a New Contact: Check if the name already exists in the dictionary. If it does, display a message; otherwise, add the new entry.
Search for a Contact: Check if the contact exists in the dictionary. If so, display the contact's phone number; otherwise, inform the user that the contact was not found.
Delete a Contact: Similar to search, but remove the contact from the dictionary if it exists.
List All Contacts: Use a loop to iterate through the dictionary and display each contact's name and phone number.
Step 5: Testing
Thoroughly test your application to ensure it handles different scenarios gracefully, such as searching for a non-existent contact or adding a contact that already exists.
Evaluation Criteria
Functionality: The application meets all the specified requirements.
Code Quality: The code is clean, well-commented, and follows standard Python conventions.
Error Handling: The application can handle incorrect user inputs without crashing.
This project is an excellent opportunity to practice the fundamental concepts of Python. By completing it, you will gain a deeper understanding of dictionaries and conditional statements, which are essential components of Python programming. Good luck!
  '''

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([text])

In [ ]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'to': 3,
 'contact': 4,
 'and': 5,
 'python': 6,
 'phonebook': 7,
 'for': 8,
 'application': 9,
 'your': 10,
 'user': 11,
 'of': 12,
 'in': 13,
 'name': 14,
 'if': 15,
 'project': 16,
 'will': 17,
 'add': 18,
 'search': 19,
 'delete': 20,
 'new': 21,
 'phone': 22,
 'number': 23,
 'it': 24,
 'display': 25,
 'step': 26,
 'dictionary': 27,
 'this': 28,
 'create': 29,
 'on': 30,
 'statements': 31,
 'text': 32,
 'all': 33,
 'contacts': 34,
 'exists': 35,
 'list': 36,
 'entries': 37,
 'conditional': 38,
 'dictionaries': 39,
 'use': 40,
 'handle': 41,
 'different': 42,
 'is': 43,
 'editor': 44,
 'code': 45,
 'be': 46,
 'by': 47,
 "contact's": 48,
 'that': 49,
 'apply': 50,
 'program': 51,
 'you': 52,
 'allow': 53,
 'understanding': 54,
 'concepts': 55,
 'store': 56,
 'actions': 57,
 'implement': 58,
 'crud': 59,
 'read': 60,
 'operations': 61,
 'requirements': 62,
 'ensure': 63,
 'exit': 64,
 'file': 65,
 'an': 66,
 'each': 67,
 'loop': 68,
 'choice': 69,
 'check': 70,
 '

In [ ]:
input_sequences = []
for sentences in text.split('\n'):
 tokenize_sentence = tokenizer.texts_to_sequences([sentences])[0]
 for i in range(1,len(tokenize_sentence)):
  input_sequences.append(tokenize_sentence[:i+1])

In [ ]:
input_sequences

[[50, 8],
 [50, 8, 73],
 [50, 8, 73, 74],
 [50, 8, 73, 74, 6],
 [50, 8, 73, 74, 6, 75],
 [50, 8, 73, 74, 6, 75, 76],
 [50, 8, 73, 74, 6, 75, 76, 51],
 [50, 8, 73, 74, 6, 75, 76, 51, 77],
 [50, 8, 73, 74, 6, 75, 76, 51, 77, 78],
 [50, 8, 73, 74, 6, 75, 76, 51, 77, 78, 13],
 [50, 8, 73, 74, 6, 75, 76, 51, 77, 78, 13, 79],
 [80, 7],
 [80, 7, 9],
 [13, 28],
 [13, 28, 16],
 [13, 28, 16, 52],
 [13, 28, 16, 52, 17],
 [13, 28, 16, 52, 17, 29],
 [13, 28, 16, 52, 17, 29, 2],
 [13, 28, 16, 52, 17, 29, 2, 82],
 [13, 28, 16, 52, 17, 29, 2, 82, 7],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83, 6],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83, 6, 28],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83, 6, 28, 9],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83, 6, 28, 9, 17],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83, 6, 28, 9, 17, 53],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9, 83, 6, 28, 9, 17, 53, 84],
 [13, 28, 16, 52, 17, 29, 2, 82, 7, 9

In [ ]:
max_len = max([len(x) for x in input_sequences])

In [ ]:
max_len

42

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
padded_input_sequences = pad_sequences(input_sequences,maxlen = max_len, padding='pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  50,   8],
       [  0,   0,   0, ...,  50,   8,  73],
       [  0,   0,   0, ...,   8,  73,  74],
       ...,
       [  0,   0,   0, ...,  12,   6, 197],
       [  0,   0,   0, ...,   6, 197, 198],
       [  0,   0,   0, ..., 197, 198, 199]], dtype=int32)

In [ ]:
X = padded_input_sequences[:,:-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  50],
       [  0,   0,   0, ...,   0,  50,   8],
       [  0,   0,   0, ...,  50,   8,  73],
       ...,
       [  0,   0,   0, ..., 196,  12,   6],
       [  0,   0,   0, ...,  12,   6, 197],
       [  0,   0,   0, ...,   6, 197, 198]], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
y

array([  8,  73,  74,   6,  75,  76,  51,  77,  78,  13,  79,   7,   9,
        28,  16,  52,  17,  29,   2,  82,   7,   9,  83,   6,  28,   9,
        17,  53,  84,   3,  18,  19,   8,  20,   5,  36,   7,  37,   1,
        16,  85,  30,  86,  10,  54,  12,  87,  88,  55,  89,  38,  31,
         5,  39,   5,  50,   6,  39,   3,  56,   7,  37,  38,  31,   3,
        41,  42,  11,  57,  59,  29,  60,  92,  20,  61,  30,   1,   7,
        37,  63,   6,  43,  93,  30,  10,  94,  44,  95,  32,  44,   8,
        96,   6,  45,  97,  98,  99, 100, 101,  32, 102,   9, 103,  46,
       104,   3,   2,  21,   4, 105,   1,  11,   8,   1,  14,   5,  22,
        23,  12,   2,  21,   4,   5,  18,  24,   3,   1,   7,   8,   2,
         4,  53,   1,  11,   3,  19,   8,   2,   4,  47,  14,   5,  25,
         1,  48,  22,  23,   2,   4, 106,   1,  11,   3,  20,   2,   4,
        47,  14,  33,  34,  25,  33,  34,  13,   1,   7, 107,   1,   9,
       109, 110, 111,  10,  16,   2,  21,   6,  65, 112,   7, 11

In [ ]:
X.shape

(440, 41)

In [ ]:
y.shape

(440,)

In [ ]:
len(tokenizer.word_index)

199

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 200)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
y.shape

(440, 200)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding

In [ ]:
model = Sequential()

In [ ]:
model.add(Embedding(200,100, input_length=41))
model.add(LSTM(150))
model.add(Dense(200,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 4s 69ms/step - accuracy: 0.0500 - loss: 5.2775
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.0750 - loss: 4.9607
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - accuracy: 0.0750 - loss: 4.7881
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - accuracy: 0.0750 - loss: 4.7512
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.0750 - loss: 4.6984
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.0773 - loss: 4.6487
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - accuracy: 0.0841 - loss: 4.5846
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.0818 - loss: 4.5090
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 122ms/step - accuracy: 0.0818 - loss: 4.4180
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 127ms/step - accuracy: 0.0727 - loss: 4.3311
Epoch 11/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.0955 - loss: 4.2332
Epoch 12/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/st

In [ ]:
message = "Python"


# tokenize
tokenize_text = tokenizer.texts_to_sequences([message])[0]
# Padding
padded_text = pad_sequences([tokenize_text],maxlen = 42,padding='pre')



In [ ]:
# Predict
import numpy as np
pos = np.argmax(model.predict(padded_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 300ms/step


In [ ]:
for word,index in tokenizer.word_index.items():
  if index == pos:
    print(word)

ensure
